### ISSUE TITLE
float division by zero

### ISSUE THREAD

**Issue by sama2689** [drukasz/RTpotter#1]
Thanks for this excellent package. I am trying to implement it on an RT-Struct file and I am getting the following error:

```
File "D:\path\RTpotter.py", line 434, in <module>
    lowerCap.append(stlfacet(kd[maxPointIdx+1],kd[maxPointIdx],kd[len(kd)-1]))

  File "D:\path\RTpotter.py", line 87, in __init__
    self.nx = nnx / ((nnx**2 + nny**2 + nnz**2)**(1/2))

ZeroDivisionError: float division by zero
```

Has this issue been encountered during development? The Rt-Struct files are from eclipse.

**Comment by drukasz** [comment]
Thank you for pointing this out, indeed it should not happen. I have not encountered this error before, looks like the program is trying to make a facet out of overlapping points... I'll take a closer look on this and post the update as soon as I'll manage to solve it.

**Comment by drukasz** [comment]
I think that the restored (in the new version 1.2) routine for removing duplicated points in each layer should prevent the described problem. I've been testing the code on various examples I have, and it worked fine. 
If the error occurs again, please let me know.

**Comment by drukasz** [comment]
It turned out that update 1.2 did not solve this issue completely. I found out that it also occurs when multiple collinear points are present in top or bottom layer. It is fixed now, hope that once for good ;)
